<?php
?>
<div class="wrap">
    <h1>Hello World!</h1>
    <p>This is a top-level menu page generated by CodeGround Plugin.</p>
    <p>Data passed by wc_get_template is <?php echo esc_html($name);?></p>
</div>