<?php
?>
<div class="wrap">
    <h1>Hello World!</h1>
    <p>This is a top-level menu page generated by CodeGround Plugin.</p>
    <p>Data passed by wc_get_template is <?php echo esc_html($name);?></p>
    <?php
//    $args = array(
//        'total_sales' => 0,
//    );
//    $products = wc_get_products( $args );
//    echo $products[0]->get_name();
    global $wpdb;
    // Define the post type
    $post_type = 'post';

    // Prepare the SQL query with a placeholder
    $query = $wpdb->prepare(
        "SELECT * FROM {$wpdb->posts} WHERE post_type = %s",
        $post_type
    );

    // Execute the query
//    $results = $wpdb->get_row($query);
//    echo "ID: {$results->ID}, Title: {$results->post_title}<br>";

    $arguments = array ('post_type'=>'post');
    $my_query = new WP_Query($arguments);

    if($my_query->have_posts()){
        while($my_query->have_posts()){
            $my_query->the_post();
            the_title('<h3>','</h3>');
        }
        wp_reset_query();
    }
    // Display results
//    if ($results) {
//        foreach ($results as $post) {
//            echo "ID: {$post->ID}, Title: {$post->post_title}<br>";
//        }
//    } else {
//        echo "No posts found.";
//    }


    ?>
</div>